export const SET_UI_KEY = 'SET_UI_KEY'
export const SET_ALERT = 'SET_ALERT'
export const SET_USER_KEY = 'SET_USER_KEY'

export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const SET_TOKEN = 'SET_TOKEN'
export const CLEAR_STATE = 'CLEAR_STATE'

export const SET_USER_LOADED = 'SET_USER_LOADED'
export const SET_USER = 'SET_USER'

export const SET_ENVIROMENTS_KEY = 'SET_ENVIROMENTS_KEY'
export const ADD_TO_ENVIROMENTS_ARRAY = 'ADD_TO_ENVIROMENTS_ARRAY'
export const UPDATE_ENVIROMENT_ARRAY_BY_ID = 'UPDATE_ENVIROMENT_ARRAY_BY_ID'
export const REMOVE_FORM_ENVIROMENTS_ARRAY_BY_KEY = 'REMOVE_FORM_ENVIROMENTS_ARRAY_BY_KEY'

export const SET_TEMPLATES_KEY = 'SET_TEMPLATES_KEY'

export const SET_LANG_KEY = 'SET_LANG_KEY'
export const SET_LANG = 'SET_LANG'
export const SET_TEXTS = 'SET_TEXTS'
export const SET_AVAILABLE_LANGS = 'SET_AVAILABLE_LANGS'
